#BNF+IAT 1.0 UTF-8;
!grammar call;
!slot <contact>;
!slot <callPre>;
!slot <callPhone>;
!slot <callTo>;
!slot <motionCommand>;
!slot <motionPre>;
!slot <direction>;
!slot <move>;
!slot <turn>;
!slot <motionAfter>;
!start <callStart>;
<callStart>:[<callPre>][<callTo>]<contact><callPhone>|[<callPre>]<callPhone>[<callTo>]<contact>|<motionPre><direction><turn>[<motionAfter>];
<contact>:张海洋;
<callPre>:我要|我想|我想要;
<callPhone>:打电话;
<callTo>:给;
<motionCommand>:跟着我;
<direction>:左|右|前|后;
<move>:来|去|动|走;
<turn>:转;
<motionPre>:向|往;
<motionAfter>:点|一点;