#BNF+IAT 1.0 UTF-8;
!grammar call;
!slot <open>;
!slot <confirm>;
!slot <download>;
!slot <uninstall>;
!slot <delete>;
!slot <pause>;
!slot <continue>;
!slot <play>;
!slot <prepage>;
!slot <nextpage>;
!slot <previous>;
!slot <next>;
!slot <volup>;
!slot <voldown>;
!slot <refresh>;
!slot <cancel>;
!slot <back>;
!slot <up>;
!slot <down>;
!slot <left>;
!slot <right>;
!slot <shutdown>;
!slot <reset>;
!slot <add>;
!slot <savewifi>;
!slot <deletewifi>;
!slot <connect>;
!slot <deletepair>;
!slot <disconnect>;
!slot <callstart>;
!start <callStart>;
 <callStart>:<open>|<confirm>|<download>|<uninstall>|<delete>|<pause>|<continue>|<play>|<prepage>|<nextpage>|<previous>|<next>|<volup>|<voldown>|<refresh>|<cancel>|<back>|<up>|<down>|<left>|<right>|<shutdown>|<reset>|<add>|<savewifi>|<deletewifi>|<connect>|<deletepair>|<disconnect>;
<open>:打开;
<confirm>:确认;
<download>:下载;
<uninstall>:卸载;
<delete>:删除;
<pause>:暂停;
<continue>:继续;
<play>:播放;
<prepage>:上一页;
<nextpage>:下一页;
<previous>:上一个;
<next>:下一个;
<volup>:调大音量;
<voldown>:调小音量;
<refresh>:刷新;
<cancel>:取消;
<back>:返回;
<up>:向上;
<down>:向下;
<left>:向左;
<right>:向右;
<shutdown>:关机;
<reset>:复位;
<add>:添加;
<savewifi>:保存网络;
<deletewifi>:删除网络;
<connect>:连接;
<deletepair>:取消配对;
<disconnect>:断开连接;
